export const INIT_CANVAS = 'initDrawInCanvas'
export const MOVE_IN_CANVAS = 'moveInCanvas'
export const DRAW_IN_CANVAS ='drawInCanvas'
export const UPLOAD_IMAGE_TO_CANVAS = 'toGrayAndResizeInCanvas'
export const CLEAR_ALL = 'clearRect'